# Машинное обучение, ФЭН ВШЭ

## Практическое задание 1

### Общая информация
Дата выдачи: 19.09.2019  

Мягкий дедлайн: 23:59MSK 27.09.2019 (за каждый день просрочки снимается 1 балл)

Жесткий дедлайн: 23:59MSK 04.10.2019

### О задании

Задание состоит из двух разделов, посвященных работе с табличными данными с помощью библиотеки pandas и визуализации с помощью matplotlib. В каждом разделе вам предлагается выполнить несколько заданий. Баллы даются за выполнение отдельных пунктов. Задачи в рамках одного раздела рекомендуется решать в том порядке, в котором они даны в задании.

Задание направлено на освоение jupyter notebook (будет использоваться в дальнейших заданиях), библиотекам pandas и matplotlib.

### Оценивание и штрафы
Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 10 баллов.

Сдавать задание после указанного срока сдачи нельзя. При выставлении неполного балла за задание в связи с наличием ошибок на усмотрение проверяющего предусмотрена возможность исправить работу на указанных в ответном письме условиях.

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов (подробнее о плагиате см. на странице курса). Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце вашей работы (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник).

### Формат сдачи
Будет объявлен позже.

## 0. Введение

Сейчас мы находимся в jupyter-ноутбуке (или ipython-ноутбуке). Это удобная среда для написания кода, проведения экспериментов, изучения данных, построения визуализаций и других нужд, не связанных с написаем production-кода. 

Ноутбук состоит из ячеек, каждая из которых может быть либо ячейкой с кодом, либо ячейкой с текстом размеченным и неразмеченным. Текст поддерживает markdown-разметку и формулы в Latex.

Для работы с содержимым ячейки используется *режим редактирования* (*Edit mode*, включается нажатием клавиши **Enter** после выбора ячейки), а для навигации между ячейками искользуется *командный режим* (*Command mode*, включается нажатием клавиши **Esc**). Тип ячейки можно задать в командном режиме либо с помощью горячих клавиш (**y** to code, **m** to markdown, **r** to edit raw text), либо в меню *Cell -> Cell type*. 

После заполнения ячейки нужно нажать *Shift + Enter*, эта команда обработает содержимое ячейки: проинтерпретирует код или сверстает размеченный текст.

In [ ]:
# ячейка с кодом, при выполнении которой появится output
2 + 2

А это ___ячейка с текстом___.

Ячейка с неразмеченыным текстом.

Попробуйте создать свои ячейки, написать какой-нибудь код и текст какой-нибудь формулой.

In [ ]:
# your code
2 + 2

Ячейка с неразмеченным текстом

Размеченный ___текст___

[Здесь](https://athena.brynmawr.edu/jupyter/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb) находится <s>не</s>большая заметка о используемом языке разметки Markdown. Он позволяет:

0. Составлять упорядоченные списки
1. #Делать 
##заголовки 
###разного уровня
3. Выделять *текст* <s>при</s> **необходимости**
4. Добавлять [ссылки](http://imgs.xkcd.com/comics/the_universal_label.png)


* Составлять неупорядоченные списки

Делать вставки с помощью LaTex:
    
$
\left\{
\begin{array}{ll}
x = 16 \sin^3 (t) \\ 
y = 13 \cos (t) - 5 \cos (2t) - 2 \cos (3t) - \cos (4t) \\
t \in [0, 2 \pi]
\end{array}
\right.$

А ещё можно вставлять картинки:
<img src="https://st2.depositphotos.com/1177973/9266/i/950/depositphotos_92668716-stock-photo-red-cat-with-computer-keyboard.jpg" style="width: 400px">

## 1. Табличные данные и Pandas

Pandas — удобная библиотека для работы с табличными данными в Python, если данных не слишком много и они помещаются в оперативную память вашего компьютера. Несмотря на неэффективность реализации и некоторые проблемы, библиотека стала стандартом в анализе данных. С этой библиотекой мы сейчас и познакомимся.

Основной объект в pandas это DataFrame, представляющий собой таблицу с именованными колонками различных типов, индексом (может быть многоуровневым). DataFrame можно создавать, считывая таблицу из файла или задавая вручную из других объектов.

В этой части потребуется выполнить несколько небольших заданий. Можно пойти двумя путями: сначала изучить материалы, а потом приступить к заданиям, или же разбираться "по ходу". Выбирайте сами.

Материалы:
1. [Pandas за 10 минут из официального руководства](http://pandas.pydata.org/pandas-docs/stable/10min.html)
2. [Документация](http://pandas.pydata.org/pandas-docs/stable/index.html) (стоит обращаться, если не понятно, как вызывать конкретный метод)
3. [Примеры использования функционала](http://nbviewer.jupyter.org/github/justmarkham/pandas-videos/blob/master/pandas.ipynb)

Многие из заданий можно выполнить несколькими способами. Не существуют единственно верного, но попробуйте максимально задействовать арсенал pandas и ориентируйтесь на простоту и понятность вашего кода. Мы не будем подсказывать, что нужно использовать для решения конкретной задачи, попробуйте находить необходимый функционал сами (название метода чаще всего очевидно). В помощь вам документация, поиск и stackoverflow.

In [ ]:
%pylab inline  
# import almost all we need
import pandas as pd

Данные можно скачать [отсюда](https://www.dropbox.com/s/5qq94wzmbw4e54r/data.csv?dl=0).

#### 1. [0.5 баллов] Откройте файл с таблицей (не забудьте про её формат). Выведите последние 10 строк.

Посмотрите на данные и скажите, что они из себя представляют, сколько в таблице строк, какие столбцы?

In [112]:
import pandas as pd
file = pd.read_csv('/Users/macosx/Desktop/Машинка/ДЗ/Датасеты/data.csv')
file.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

Данные представляют собой выборку из 4622 зарегистрированных покупок конкретных товаров в продуктовом магазине. При этом в каждом наблюдении есть id заказа, в рамках которого был приобритён продукт, его кол-во в рамках одной покупки, название самого продукта, его описание и цена (матрица 4622 на 5)

In [113]:
print(file.shape)

(4622, 5)

________

#### 2. [0.25 баллов] Ответьте на вопросы:
1. Сколько заказов попало в выборку?
2. Сколько уникальных категорий товара было куплено? (item_name)

In [114]:
print('Кол-во уникальных заказов — ', file['order_id'].nunique())
print('Уникальных категорий товара — ', file['item_name'].nunique())

Кол-во уникальных заказов —  1834
Уникальных категорий товара —  50

#### 3. [0.25 баллов] Есть ли в данных пропуски? В каких колонках?

In [115]:
print(file.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB
None

Пропуски есть только в колонке "choice_description", так как в остальных кол-во не NaN-значений равно кол-ву строк в Датасете

____________

Заполните пропуски пустой строкой для строковых колонок и нулём для числовых.

In [116]:
file['choice_description'] = file.choice_description.fillna('')
file.tail(10)

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,,$2.15
4614,1831,1,Bottled Water,,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### 4. [0.5 баллов] Посмотрите внимательнее на колонку с ценой товара. Какого она типа? Создайте новую колонку так, чтобы в ней цена была числом.

Для этого попробуйте применить функцию-преобразование к каждой строке вашей таблицы (для этого есть соответствующая функция).

__ __ __

Из пунктов выше становится понятно, что переменные являются типами object, то есть представленны в виде текста. Но это также можно выяснить при помощи.dtype

In [117]:
file.dtypes

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [118]:
new_price = file['item_price']
file['New_price'] = new_price
file['New_price'] = file.New_price.apply(lambda x: x.replace('$', ''))
file['New_price'] = pd.to_numeric(file['New_price'], errors='coerce')
file.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price             object
New_price             float64
dtype: object

Теперь новая создана новая колонка с ценой, где все данные - числовые 
______

Какая средняя/минимальная/максимальная цена у товара?

In [119]:
print('Средняя цена товара - $', file['New_price'].mean())
print('Максимальная цена товара - $', file['New_price'].max())
print('Минимальная цена товара - $', file['New_price'].min())

Средняя цена товара - $ 7.464335785374397
Максимальная цена товара - $ 44.25
Минимальная цена товара - $ 1.09

_____

Удалите старую колонку с ценой.

In [120]:
file = file.drop('item_price', axis=1)
file.head()

,order_id,quantity,item_name,choice_description,New_price
0,1,1,Chips and Fresh Tomato Salsa,,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

#### 5. [0.25 баллов] Какие 5 товаров были самыми дешёвыми и самыми дорогими? (по item_name)

Для этого будет удобно избавиться от дубликатов и отсортировать товары. Не забудьте про количество товара.

In [124]:
def quantification(x):
    return x / file['quantity']
file = file.sort_values(by=['New_price'])
file

,order_id,quantity,item_name,choice_description,New_price
1140,471,1,Bottled Water,,1.09
3020,1201,1,Canned Soda,[Diet Dr. Pepper],1.09
2850,1132,1,Canned Soda,[Diet Coke],1.09
1030,424,1,Canned Soda,[Diet Dr. Pepper],1.09
3575,1434,1,Canned Soda,[Dr. Pepper],1.09
2443,971,1,Canned Soda,[Coca Cola],1.09
3576,1434,1,Canned Soda,[Coca Cola],1.09
2493,990,1,Canned Soda,[Coca Cola],1.09
3740,1494,1,Canned Soda,[Sprite],1.09
3718,1485,1,Canned Soda,[Diet Dr. Pepper],1.09
2815,1117,1,Bottled Water,,1.09
370,160,1,Canned Soda,[Diet Coke],1.09
2814,1117,1,Canned Soda,[Diet Dr. Pepper],1.09
3145,1254,1,Canned Soda,[Diet Dr. Pepper],1.09
1431,579,1,Canned Soda,[Sprite],1.09
956,392,1,Canned Soda,[Coca Cola],1.09
943,388,1,Bottled Water,,1.09
807,332,1,Canned Soda,[Mountain Dew],1.09
2584,1025,1,Canned Soda,[Mountain Dew],1.09
3936,1578,1,Canned Soda,[Diet Dr. Pepper],1.09
1511,614,1,Canned Soda,[Mountain Dew],1.09
126,55,1,Canned Soda,[Coca Cola],1.09
3006,1195,1,Canned Soda,[Coca Cola],1.09
780,321,1,Bottled Water,,1.09
34,17,1,Bottled Water,,1.09
3715,1484,1,Canned Soda,[Dr. Pepper],1.09
779,321,1,Canned Soda,[Diet Coke],1.09
2410,955,1,Bottled Water,,1.09
3667,1467,1,Bottled Water,,1.09
3793,1518,1,Canned Soda,[Diet Coke],1.09
...,...,...,...,...,...
1429,578,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...",22.50
3507,1409,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",22.50
2510,997,2,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",22.50
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50
1110,459,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",22.50
864,357,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",22.50
591,243,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, So...",22.50
213,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",22.50
633,261,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",22.50
2954,1175,2,Steak Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",22.96
4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50
506,212,2,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",23.50
3754,1502,2,Steak Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.50
1753,708,2,Steak Burrito,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",23.50
4307,1718,2,Steak Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",23.50
1566,635,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",23.50
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78
613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.78
3334,1336,3,Steak Bowl,"[Tomatillo Green Chili (Medium), [Rice, Black ...",26.07
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",26.25
3634,1454,3,Chicken Burrito,[Fresh Tomato Salsa],26.25
3636,1454,3,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",26.25
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",27.75
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",27.75
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
3598,1443,15,Chips and Fresh Tomato Salsa,,44.25

#### 6. [0.5 баллов] Какой средний чек у заказа? Сколько в среднем товаров покупают?

Если необходимо провести вычисления в терминах заказов, то будет удобно сгруппировать строки по заказам и посчитать необходимые статистики.

In [ ]:
# your code

#### 7. [0.25 баллов] Сколько заказов содержали ровно 1 товар?

In [ ]:
# your code

#### 8. [0.75 баллов] Создайте новый DateFrame из матрицы, созданной ниже. Назовите колонки index, column1, column2 и сделайте первую колонку индексом.

In [ ]:
data = np.random.rand(10, 3)

# your code

Сохраните DataFrame на диск в формате csv без индексов и названий столбцов.

In [ ]:
# your code

## 2. Визуализации и matplotlib

При работе с данными часто неудобно делать какие-то выводы, если смотреть на таблицу и числа в частности, поэтому важно уметь визуализировать данные. В этом разделе мы этим и займёмся.

У matplotlib, конечно, же есть [документация](https://matplotlib.org/users/index.html) с большим количеством [примеров](https://matplotlib.org/examples/), но для начала достаточно знать про несколько основных типов графиков:
- plot — обычный поточечный график, которым можно изображать кривые или отдельные точки;
- hist — гистограмма, показывающая распределение некоторое величины;
- scatter — график, показывающий взаимосвязь двух величин;
- bar — столбцовый график, показывающий взаимосвязь количественной величины от категориальной.

В этом задании вы попробуете построить каждый из них. Не менее важно усвоить базовые принципы визуализаций:
- на графиках должны быть подписаны оси;
- у визуализации должно быть название;
- если изображено несколько графиков, то необходима поясняющая легенда;
- все линии на графиках должны быть чётко видны (нет похожих цветов или цветов, сливающихся с фоном);
- если отображена величина, имеющая очевидный диапазон значений (например, проценты могут быть от 0 до 100), то желательно масштабировать ось на весь диапазон значений (исключением является случай, когда вам необходимо показать малое отличие, которое незаметно в таких масштабах).
- сетка на графике помогает оценить значения в точках на глаз, это обычно полезно, поэтому лучше ее отрисовывать.

In [ ]:
%matplotlib inline  # нужно для отображения графиков внутри ноутбука
import matplotlib.pyplot as plt

На самом деле мы уже импортировали matplotlib внутри %pylab inline в начале задания.

Работать мы будем с той же выборкой покупкок. Добавим новую колонку с датой покупки.

In [130]:
import datetime

start = datetime.datetime(2018, 1, 1)
end = datetime.datetime(2018, 1, 31)
delta_seconds = int((end - start).total_seconds())

dates = pd.DataFrame(index=file.order_id.unique())
dates['date'] = [
    (start + datetime.timedelta(seconds=random.randint(0, delta_seconds))).strftime('%Y-%m-%d')
    for _ in range(file.order_id.nunique())]

# если DataFrame с покупками из прошлого заказа называется не df, замените на ваше название ниже
file['date'] = file.order_id.map(dates['date'])
file

NameError: name 'random' is not defined

#### 1. [1 балл] Постройте гистограмму распределения сумм покупок и гистограмму средних цен отдельных видов продуктов item_name. 

Изображайте на двух соседних графиках. Для этого может быть полезен subplot.

,order_id,quantity,item_name,choice_description,New_price
1140,471,1,Bottled Water,,1.09
3020,1201,1,Canned Soda,[Diet Dr. Pepper],1.09
2850,1132,1,Canned Soda,[Diet Coke],1.09
1030,424,1,Canned Soda,[Diet Dr. Pepper],1.09
3575,1434,1,Canned Soda,[Dr. Pepper],1.09
2443,971,1,Canned Soda,[Coca Cola],1.09
3576,1434,1,Canned Soda,[Coca Cola],1.09
2493,990,1,Canned Soda,[Coca Cola],1.09
3740,1494,1,Canned Soda,[Sprite],1.09
3718,1485,1,Canned Soda,[Diet Dr. Pepper],1.09
2815,1117,1,Bottled Water,,1.09
370,160,1,Canned Soda,[Diet Coke],1.09
2814,1117,1,Canned Soda,[Diet Dr. Pepper],1.09
3145,1254,1,Canned Soda,[Diet Dr. Pepper],1.09
1431,579,1,Canned Soda,[Sprite],1.09
956,392,1,Canned Soda,[Coca Cola],1.09
943,388,1,Bottled Water,,1.09
807,332,1,Canned Soda,[Mountain Dew],1.09
2584,1025,1,Canned Soda,[Mountain Dew],1.09
3936,1578,1,Canned Soda,[Diet Dr. Pepper],1.09
1511,614,1,Canned Soda,[Mountain Dew],1.09
126,55,1,Canned Soda,[Coca Cola],1.09
3006,1195,1,Canned Soda,[Coca Cola],1.09
780,321,1,Bottled Water,,1.09
34,17,1,Bottled Water,,1.09
3715,1484,1,Canned Soda,[Dr. Pepper],1.09
779,321,1,Canned Soda,[Diet Coke],1.09
2410,955,1,Bottled Water,,1.09
3667,1467,1,Bottled Water,,1.09
3793,1518,1,Canned Soda,[Diet Coke],1.09
...,...,...,...,...,...
1429,578,2,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...",22.50
3507,1409,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",22.50
2510,997,2,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",22.50
135,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",22.50
1110,459,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",22.50
864,357,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",22.50
591,243,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, So...",22.50
213,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",22.50
633,261,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",22.50
2954,1175,2,Steak Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",22.96
4427,1764,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Sour ...",23.50
506,212,2,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",23.50
3754,1502,2,Steak Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.50
1753,708,2,Steak Burrito,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",23.50
4307,1718,2,Steak Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",23.50
1566,635,2,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",23.50
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",23.78
613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",23.78
3334,1336,3,Steak Bowl,"[Tomatillo Green Chili (Medium), [Rice, Black ...",26.07
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",26.25
3634,1454,3,Chicken Burrito,[Fresh Tomato Salsa],26.25
3636,1454,3,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",26.25
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",27.75
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",27.75
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",32.94
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
3598,1443,15,Chips and Fresh Tomato Salsa,,44.25

#### 2. [1 балл] Постройте график зависимости суммы покупок от дней.

In [ ]:
# your code

#### 3. [1 балл] Постройте средних сумм покупок по дням недели (bar plot).

In [ ]:
# your code

#### 4. [1 балл] Постройте график зависимости денег за товар от купленного количества (scatter plot).

In [ ]:
# your code

Сохраните график в формате pdf (так он останется векторизованным).

In [ ]:
# your code

Еще одна билиотека для визуализации: [seaborn](https://jakevdp.github.io/PythonDataScienceHandbook/04.14-visualization-with-seaborn.html). Это настройка над matplotlib, иногда удобнее и красивее делать визуализации через неё.